project_id = "pmumdlscexdlunkoyhqw"

[functions.send-message]
verify_jwt = false

[functions.log-to-solana]
verify_jwt = false

[functions.verify-token-balance]
verify_jwt = false

[functions.verify-zk-proof]
verify_jwt = false

[functions.upload-verification-key]
verify_jwt = false
